name:                apus
version:             0.1.0.0
github:              "githubuser/apus"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/apus#readme>

dependencies:
- aeson
- binary
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- containers
- Diff
- directory
- drinkery
- extensible
- filepath
- hashable
- http-client
- http-client-tls
- http-types
- JuicyPixels
- JuicyPixels-extra
- lens
- liszt
- rio
- stm
- text
- time
- transformers
- unordered-containers
- wai
- wai-middleware-static
- wai-websockets
- warp
- warp-tls
- websockets
- winery
- yaml

default-extensions:
- OverloadedStrings
- DeriveGeneric
- RecordWildCards
- NoImplicitPrelude
- LambdaCase

executables:
  apus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -Wall
    - -O2
